app1/urls.py
from django.urls import path
from app1.views import *
app_name="haipage"

urlpatterns=[
    path("hai/",hai,name='hai'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app1/",include("app1.urls")),
    path("hello/",hello,name="hello"),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request,"hello.html")

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to hai page</h1>
        <h2><a href="{% url 'hello' %}">click to go hello page</a></h2>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to hello page</h1>
        <h2><a href="{% url 'haipage:hai' %}">click to go hai page</a></h2>
    </center>
</body>
</html>